version: '3'

services:
  db:
    image: postgres:13.1-alpine
    hostname: axione-postgres
    container_name: axione-postgres
    environment:
      - POSTGRES_USER=axione
      - POSTGRES_PASSWORD=axione
      - POSTGRES_DB=axione_database
    volumes:
      - db_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: entrypoints/entrypoint.sh
    hostname: axione-app
    container_name: axione-app
    volumes:
      - ./src:/src
      - ./entrypoints:/src/entrypoints
    ports:
      - "8000:8000"

volumes:
  db_data: